# Generated by Django 3.1.1 on 2020-09-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descriprion',
            new_name='description',
        ),
    ]
